---
- name: "Re tag old AMIs"
  ec2_tag:
    region: "us-east-2"
    resource: "{{item.image_id}}"
    state: present
    tags:
      latest: "false"
  with_items: "{{ami.images}}"

- ec2_ami:
    instance_id: "{{instance_id}}"
    no_reboot: yes
    wait: yes
    name: "{{ami_tags.Name}}-{{ lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
    tags: "{{ami_tags}}"
