---
- name: "Re tag old AMIs"
  ec2_tag:
    region: "{{ec2_region}}"
    resource: "{{item.image_id}}"
    state: present
    tags:
      latest: "false"
  with_items: "{{ami.images}}"
  when: ami.images|length > 0

- name: Stop instance before baking AMI
  ec2:
    state: 'stopped'
    region: "{{ec2_region}}"
    instance_ids: "{{instance_id}}"

- name: sleep for 45 seconds and continue with play
  wait_for: timeout=45
  delegate_to: localhost

- name: "Create AMI with new version"
  ec2_ami:
    instance_id: "{{instance_id}}"
    no_reboot: yes
    wait: yes
    name: "{{ami_tags.Name}}-{{ lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
    tags: "{{ami_tags}}"
