- debug:
    var: item.creation_date
  with_items: "{{ami}}"
  
- set_fact:
    keep_amis: "{{amis[:keep_last]}}"

- name: "Delete old AMIs"
  ec2_ami:
    image_id: "{{item.image_id}}"
    delete_snapshot: yes
    state: absent
  with_items: amis
  when: item not in keep_amis
