---
- name: Terminate instances that were previously launched
  ec2:
    state: 'absent'
    region: "{{ec2_region}}"
    instance_ids: '{{ item.instance_id }}'
  with_items: "{{ec2_instances.instances}}"
