---
#### CREATE
- ec2:
    instance_profile_name: "{{ec2_instance_profile_name}}"
    key_name: "{{ec2_key}}"
    group: "{{ec2_security_groups}}"
    instance_type: "{{ec2_instance_type}}"
    region: "{{instance_region}}"
    image: "{{ec2_ami}}"
    wait: "{{ec2_wait}}"
    exact_count: "{{ec2_count}}"
    count_tag: "{{ec2_count_tags}}"
    wait_timeout: "{{ec2_wait_timeout}}"
    instance_tags: "{{ec2_tags}}"
    vpc_subnet_id: "{{ec2_subnet}}"
    state: "{{ec2_state}}"
  register: ec2_instance


- name: Wait for SSH to come up
  local_action: wait_for
                host="{{ item.private_ip }}"
                port="{{ec2_ssh_port}}"
                state=started
  with_items: "{{ec2_instance.tagged_instances}}"
  when: ec2_state == "started"
